# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

brands = Brand.create([{ name: 'Canon' }, { name: 'Kodak' }, { name: 'Sony'}, {name:'HP'},{name:'Samsung'}])

categories = Category.create([{ name: 'Electronics' }, { name: 'Books' }, { name: 'Appliances' }, { name: 'Furniture' }, { name: 'Apparel & Accessories'}, { name: 'Health & Beauty' }])

subcategories = Subcategory.create([{ category_id: '1', name: 'Laptops' }, { category_id: '1', name: 'Cameras' }, { category_id: '1', name: 'Mobiles' }, { category_id: '1', name: 'Headphones' }, { category_id: '2', name: 'Fiction' }, { category_id: '2', name: 'Non-Fiction' },{ category_id: '2', name: 'Magazines' },{ category_id: '2', name: 'Textbooks' },{ category_id: '3', name: 'Microwaves' },{ category_id: '3', name: 'Irons' },{ category_id: '3', name: 'Toasters' }, { category_id: '4', name: 'Tables' }, { category_id: '4', name: 'Chairs' },{ category_id: '4', name: 'Bedframes' }, { category_id: '4', name: 'Mattresses' },{ category_id: '5', name: 'Clothing'}, { category_id: '5', name: 'Shoes' },{ category_id: '5', name: 'Handbags' },{ category_id: '5', name: 'Luggage' },{ category_id: '5', name: 'Jewellery'}])

items = Item.create([{ brand_id: '1', category_id: '1', subcategory_id: '2', name: 'Canon EOS Rebel T3i / 600D 18.0 MP Digital SLR Camera - Black (Kit w/ EF-S IS II 18-55mm Lens)', description: 'Capture all your special moments with the Canon EOS Rebel T3i/600D DSLR camera and cherish the memories over and over again.', image: 'item.JPG', start_price: 1100, instant_price: 1780, quantity: 7, sale_type: 'auction', start_time: '2012-10-02', end_time: '2012-10-29' }, { brand_id: '2', category_id: '1', subcategory_id: '2', name: 'Kodak EASYSHARE C183 14.0 MP Digital Camera - Black', description: 'Share your world big and bright with the Kodak EASYSHARE C183 Digital Camera. Now sharing your life in amazing detail is as simple as pressing a button.', image: 'item2.jpg' }, { brand_id: '3', category_id: '1', subcategory_id: '2', name: 'Sony Cyber-shot DSC-W650 16MP 5X Opt Zoom Black Digital Camera 720p HD Video', description: 'Get high-quality images with the Sony Cyber-shot DSC-W650 digital camera. Boasting a 5x optical zoom, this 16.1 MP digital camera produces detailed photos.', image: 'item3.JPG'},{ brand_id: '4', category_id: '1', subcategory_id: '1', name: 'HP Pavilion g7-2010nr 17.3-Inch Laptop (Black)', description: 'Product Features- Intel Core_i3_2350M Processor 2.3GHz (3MB Cache);6 GB SDRAM RAM; Weight: 4.6 lbs; 640GB 5400rpm Hard Drive; 17.3-Inch Screen; Intel HD Graphics 3000; Windows 7 Home Premium 64-bit', image: 'item4.jpg', start_price: 700, instant_price: 820, quantity: 10, sale_type: 'Auction', start_time: '2012-10-02', end_time: '2012-10-29' },{ brand_id: '5', category_id: '1', subcategory_id: '3', name: 'Samsung Galaxy S III/S3 GT-I9300 Factory Unlocked Phone - International Version (Ceramic White)', description: 'Product Features- 2G Network GSM 850 / 900 / 1800 / 1900; 3G Network HSDPA 850 / 900 / 1900 / 2100; 4G Network Region Based; Dimensions 136.6 x 70.6 x 8.6mm; Internal storage capacity: 16 GB', image: 'item5.jpg', start_price: 400, instant_price: 450, quantity: 20, sale_type: 'Auction', start_time: '2012-10-02', end_time: '2012-10-29' }])