require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BidsController do

  # This should return the minimal set of attributes required to create a valid
  # Bid. As you add validations to Bid, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BidsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bid" do
        expect {
          post :create, {:bid => valid_attributes}, valid_session
        }.to change(Bid, :count).by(1)
      end

      it "assigns a newly created bid as @bid" do
        post :create, {:bid => valid_attributes}, valid_session
        assigns(:bid).should be_a(Bid)
        assigns(:bid).should be_persisted
      end

      it "redirects to the created bid" do
        post :create, {:bid => valid_attributes}, valid_session
        response.should redirect_to(Bid.last)
      end
    end

  end

end
